---
#1 проверяем наличие точки монтирования
- name: check mountpoint exist
  ansible.builtin.file:
    path: "{{ mountpoint }}"
    state: directory
    mode: '0755'
    owner: root
    group: root

#2 проверяем наличие каталога для архивирования
- name: check mountpoint exist
  ansible.builtin.file:
    path: "{{ dest }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
