---

# 1. Копируем файл с учетными данными
- name: Copy 
  ansible.builtin.template:
    src: files/credentials
    dest:  "/etc/credentials_backup"
    owner: root
    group: root
    mode: '0444'

#2 Монтируем сетевой диск
- name: "mount share"
  ansible.posix.mount:
    state:   "mounted"
    fstype:  "cifs"
    name:    "{{ mountpoint }}"
    src:     "{{ uri }}"
    opts:    "credentials=/etc/credentials_backup,file_mode=0644,dir_mode=0755,gid=root,uid=root"
    boot:    "no"

